#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FlightDB")]
public partial class FlightDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertflightorder(flightorder instance);
  partial void Updateflightorder(flightorder instance);
  partial void Deleteflightorder(flightorder instance);
  partial void Insertflightuser(flightuser instance);
  partial void Updateflightuser(flightuser instance);
  partial void Deleteflightuser(flightuser instance);
  #endregion
	
	public FlightDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FlightDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public FlightDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FlightDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FlightDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FlightDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<flightinfo> flightinfos
	{
		get
		{
			return this.GetTable<flightinfo>();
		}
	}
	
	public System.Data.Linq.Table<flightorder> flightorders
	{
		get
		{
			return this.GetTable<flightorder>();
		}
	}
	
	public System.Data.Linq.Table<flightuser> flightusers
	{
		get
		{
			return this.GetTable<flightuser>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightinfo")]
public partial class flightinfo
{
	
	private int _id;
	
	private string _depcity;
	
	private System.DateTime _depdate;
	
	private System.TimeSpan _deptime;
	
	private string _depsymbol;
	
	private string _destcity;
	
	private string _destsymbol;
	
	private System.DateTime _arrdate;
	
	private System.TimeSpan _arrtime;
	
	private System.DateTime _retdate;
	
	private System.TimeSpan _rettime;
	
	private string _airline;
	
	private string _class;
	
	private int _stops;
	
	private string _duration;
	
	private decimal _price;
	
	public flightinfo()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depcity", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string depcity
	{
		get
		{
			return this._depcity;
		}
		set
		{
			if ((this._depcity != value))
			{
				this._depcity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depdate", DbType="Date NOT NULL")]
	public System.DateTime depdate
	{
		get
		{
			return this._depdate;
		}
		set
		{
			if ((this._depdate != value))
			{
				this._depdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptime", DbType="Time NOT NULL")]
	public System.TimeSpan deptime
	{
		get
		{
			return this._deptime;
		}
		set
		{
			if ((this._deptime != value))
			{
				this._deptime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depsymbol", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string depsymbol
	{
		get
		{
			return this._depsymbol;
		}
		set
		{
			if ((this._depsymbol != value))
			{
				this._depsymbol = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destcity", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string destcity
	{
		get
		{
			return this._destcity;
		}
		set
		{
			if ((this._destcity != value))
			{
				this._destcity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destsymbol", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string destsymbol
	{
		get
		{
			return this._destsymbol;
		}
		set
		{
			if ((this._destsymbol != value))
			{
				this._destsymbol = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrdate", DbType="Date NOT NULL")]
	public System.DateTime arrdate
	{
		get
		{
			return this._arrdate;
		}
		set
		{
			if ((this._arrdate != value))
			{
				this._arrdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrtime", DbType="Time NOT NULL")]
	public System.TimeSpan arrtime
	{
		get
		{
			return this._arrtime;
		}
		set
		{
			if ((this._arrtime != value))
			{
				this._arrtime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_retdate", DbType="Date NOT NULL")]
	public System.DateTime retdate
	{
		get
		{
			return this._retdate;
		}
		set
		{
			if ((this._retdate != value))
			{
				this._retdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rettime", DbType="Time NOT NULL")]
	public System.TimeSpan rettime
	{
		get
		{
			return this._rettime;
		}
		set
		{
			if ((this._rettime != value))
			{
				this._rettime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airline", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string airline
	{
		get
		{
			return this._airline;
		}
		set
		{
			if ((this._airline != value))
			{
				this._airline = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string @class
	{
		get
		{
			return this._class;
		}
		set
		{
			if ((this._class != value))
			{
				this._class = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stops", DbType="Int NOT NULL")]
	public int stops
	{
		get
		{
			return this._stops;
		}
		set
		{
			if ((this._stops != value))
			{
				this._stops = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string duration
	{
		get
		{
			return this._duration;
		}
		set
		{
			if ((this._duration != value))
			{
				this._duration = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,0) NOT NULL")]
	public decimal price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightorder")]
public partial class flightorder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _username;
	
	private string _email;
	
	private int _confirmationnumber;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnconfirmationnumberChanging(int value);
    partial void OnconfirmationnumberChanged();
    #endregion
	
	public flightorder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confirmationnumber", DbType="Int NOT NULL")]
	public int confirmationnumber
	{
		get
		{
			return this._confirmationnumber;
		}
		set
		{
			if ((this._confirmationnumber != value))
			{
				this.OnconfirmationnumberChanging(value);
				this.SendPropertyChanging();
				this._confirmationnumber = value;
				this.SendPropertyChanged("confirmationnumber");
				this.OnconfirmationnumberChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightuser")]
public partial class flightuser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _firstname;
	
	private string _middlename;
	
	private string _lastname;
	
	private string _username;
	
	private string _email;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnmiddlenameChanging(string value);
    partial void OnmiddlenameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public flightuser()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middlename", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string middlename
	{
		get
		{
			return this._middlename;
		}
		set
		{
			if ((this._middlename != value))
			{
				this.OnmiddlenameChanging(value);
				this.SendPropertyChanging();
				this._middlename = value;
				this.SendPropertyChanged("middlename");
				this.OnmiddlenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
